import { StyleSheet, Platform, Dimensions } from "react-native";
const height = Dimensions.get("window").height;
export const stylesGlobal = StyleSheet.create({
  highLightText: {
    fontFamily: "Exo2_400Regular",
    fontSize: 13,
    opacity: 0.5,
  },
  header: {
    fontSize: 20,
    color: "#434343",
    paddingHorizontal: 15,
    width: "95%",
    fontFamily: "Exo2_700Bold",
  },
  buttonText: {
    flexDirection: "row",
    fontSize: 16,
    color: "#545454",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Exo2_700Bold",
    textAlign: "center",
  },
  animatedButton: {
    backgroundColor: "#e5f5f2",
    top: 15,
    overflow: "hidden",
    flex: 1,
    width: "95%",
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 24,
    marginBottom: 10,
    height: 45,
  },
  container: {
    backgroundColor: "white",
    position: "relative",
  },
  logo: {
    flex: 1,
    marginTop: 35,
    marginBottom: 20,
    marginLeft: 20,
  },
  header2: {
    fontSize: 20,
    paddingHorizontal: 15,
    marginBottom: 25,
    color: "#434343",
    fontFamily: "Exo2_700Bold",
  },
  button: {
    flex: 1,
    marginTop: 5,
    overflow: "hidden",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#c0c0c0",
    color: "blue",
    borderRadius: 24,
    marginBottom: 10,
    height: 45,
  },
  checkboxContainer: {
    flexDirection: "row",
    marginBottom: 10,
    width: "100%",
    alignSelf: "center",
  },
  checkbox: {
    marginTop: 10,
  },
  textArea: {
    fontFamily: "Exo2_700Bold",
    fontSize: 12,
    marginTop: 15,
    marginRight: 5,
    marginLeft: -15,
  },

  input: {
    marginTop: 15,
    paddingLeft: 10,
    height: Platform.OS === "ios" ? 56 : null,
    width: "100%",
    alignSelf: "center",
    fontFamily: "Exo2_700Bold",
  },
  textBold: {
    fontFamily: "Exo2_700Bold",
    color: "#434343",
    fontSize: 14,
  },
  textRegular: {
    fontFamily: "Exo2_400Regular",
    color: "#434343",
    fontSize: 12,
  },
});

export const stylesAddAccount = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    zIndex: 2,
    position: "relative",
  },
  logo: {
    flex: 1,

    marginLeft: 13,
    position: "relative",
  },
  header: {
    position: "relative",
    fontSize: 20,
    marginLeft: 7,
    fontWeight: "700",
    color: "#434343",
    marginBottom: 15,
  },
  header2: {
    fontSize: 20,
    marginLeft: 15,
    fontWeight: 700,
    marginBottom: 25,
    fontFamily: "Exo2_600SemiBold",
  },
  buttonPressed: {
    opacity: 0.5,
    width: "100%",
    height: "100%",
    flex: 1,
    alignItems: "center",
    flexDirection: "row",
  },
  buttonNotPressed: {
    width: "100%",
    flex: 1,
    alignItems: "center",
    height: "100%",
    flexDirection: "row",
  },
  button1: {
    width: "95%",
    borderWidth: 1,
    alignSelf: "center",
    alignItems: "center",
    flexDirection: "row",
    borderColor: "#c0c0c0",
    height: "15%",
    borderRadius: 4,
  },
  buttonText: {
    flexDirection: "row",
    fontSize: 16,
    paddingLeft: 5,
    color: "#434343",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Exo2_700Bold",
    textAlign: "center",
  },
  buttonOther: {
    height: "15%",
    justifyContent: "center",
    paddingVertical: 10,
    alignSelf: "center",
    width: "95%",
    paddingHorizontal: 10,
    borderWidth: 2,
    borderColor: "#c0c0c0",
    borderRadius: 4,
    marginBottom: 50,
  },
  buttonTextOther: {
    fontSize: 16,
    color: "#434343",
    fontFamily: "Exo2_700Bold",
  },
  buttonTextMini: {
    fontSize: 13,
    fontFamily: "Exo2_400Regular",
    color: "#434343",
    opacity: 0.5,
  },
  buttonTextMiniOther: {
    fontSize: 13,
    opacity: 0.5,
    fontFamily: "Exo2_400Regular",
    color: "#434343",
  },
  checkboxContainer: {
    flexDirection: "row",
    marginBottom: 10,
  },
  checkbox: {
    marginTop: 10,
  },
  textArea: {
    fontFamily: "Exo2_600SemiBold",
    fontSize: 12,
    marginTop: 15,
    marginRight: 5,
    marginLeft: -20,
  },

  input: {
    height: 50,
    marginTop: 10,
    marginLeft: 15,
    marginRight: 15,
    color: "white",
    fontFamily: "Exo2_600SemiBold",
  },
  url: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
});

export const stylesSuccessScreen = StyleSheet.create({
  container: {
    flex: 1,
    // width: "100%",
    height: 500,
    backgroundColor: "white",
    // zIndex: 2,
    // elevation: 0,
    // position: "relative",
  },
  logo: {
    flex: 1,
    marginTop: 35,
    marginBottom: 20,
    marginLeft: 13,
    position: "relative",
  },
  header: {
    position: "relative",
    fontSize: 20,
    marginLeft: 11,
    fontWeight: "700",
    marginTop: 20,
    color: "#434343",
    fontFamily: "Exo2_700Bold",
    marginBottom: 15,
  },
  header2: {
    fontSize: 12,
    fontFamily: "Exo2_400Regular",
    marginLeft: 12,
    marginBottom: 25,
    color: "#434343",
  },
  button1: {
    zIndex: 2,
    flexDirection: "row",
    width: 340,
    alignItems: "center",
    marginLeft: 12,
    marginRight: 12,
    height: 61,
    borderWidth: 3,
    borderColor: "#c0c0c0",
    marginBottom: 13,
    marginTop: 5,
    borderRadius: 4,
  },
  button2: {
    flexDirection: "row",
    width: 340,
    alignItems: "center",
    marginLeft: 12,
    marginRight: 12,
    height: 61,
    borderWidth: 3,
    borderColor: "#c0c0c0",
    marginBottom: 13,
    marginTop: 5,
    borderRadius: 4,
  },
  button3: {
    flexDirection: "row",
    width: 340,
    alignItems: "center",
    marginLeft: 12,
    marginRight: 12,
    height: 61,
    borderWidth: 3,
    borderColor: "#c0c0c0",
    marginBottom: 13,
    marginTop: 5,
    borderRadius: 4,
  },
  buttonText: {
    marginLeft: 10,
    flexDirection: "row",
    fontSize: 16,
    color: "black",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Exo2_600SemiBold",
    textAlign: "center",
  },
  buttonOther: {
    width: 340,
    alignItems: "center",
    marginLeft: 12,
    marginRight: 12,
    height: 61,
    borderWidth: 3,
    borderColor: "#c0c0c0",
    marginBottom: 13,
    marginTop: 5,
    // color: "red",
    borderRadius: 4,
  },
  buttonTextOther: {
    marginTop: 5,
    marginLeft: -33,
    fontSize: 16,
    color: "black",
    fontFamily: "Exo2_600SemiBold",
    textAlign: "left",
  },
  buttonTextMini: {
    marginTop: 2,
    fontSize: 13,
    marginLeft: 2,
    color: "#c0c0c5",
    textAlign: "left",
  },
  buttonTextMiniOther: {
    fontSize: 13,
    marginLeft: -200,
    color: "#c0c0c0",
    textAlign: "left",
  },
  checkboxContainer: {
    flexDirection: "row",
    marginBottom: 10,
  },
  checkbox: {
    marginTop: 10,
  },
  textArea: {
    fontFamily: "Exo2_600SemiBold",
    fontSize: 12,
    marginTop: 15,
    marginRight: 5,
    marginLeft: -20,
  },

  input: {
    height: 50,
    marginTop: 10,
    marginLeft: 15,
    marginRight: 15,
    color: "white",
    fontFamily: "Exo2_600SemiBold",
  },
  url: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
});
